#!/bin/bash
# To be executed on startup to configure chanchan cluster
### BEGIN INIT INFO
# Provides:          configure-chanchan-cluster
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop configure-chanchan-cluster
# Description:       Start/stop configure-chanchan-cluster
### END INIT INFO

. /lib/lsb/init-functions

# orgs secrets key from IDM
CC_APP_CLIENT_PATH="fiware-chanchan/client"
CC_OAUTH_CREDENTIALS="/config/appoauth.txt"
DEPLOY_USER=bitergia

if [ -f "${CC_OAUTH_CREDENTIALS}" ]; then
    ORGANIZATIONS=$( (echo "{" ; (cat "${CC_OAUTH_CREDENTIALS}" | paste -s -d ',') ; echo "}")  | python -m json.tool )
    su - ${DEPLOY_USER} <<EOF
cat << __EOF > ${CC_APP_CLIENT_PATH}/app/orgs.json
${ORGANIZATIONS}
__EOF
EOF
fi

# IDM host
IDM_HOST='idmauthlegacy'
IDM_HOST_IMAGE=`cat /config/idm_host_docker_image`
su - ${DEPLOY_USER} <<EOF
cp ${CC_APP_CLIENT_PATH}/app/hosts.json.example ${CC_APP_CLIENT_PATH}/app/hosts.json
sed -i ${CC_APP_CLIENT_PATH}/app/hosts.json \
    -e  "s/\"idm\":\"localhost\"/\"idm\":\"${IDM_HOST}\"/" \
    -e  "s/\"idm_host_docker_image\":\"localhost\"/\"idm_host_docker_image\":\"idm.${IDM_HOST_IMAGE}\"/"
EOF