#!/bin/bash
# To be executed on startup to configure chanchan cluster
### BEGIN INIT INFO
# Provides:          configure-chanchan-cluster
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop configure-chanchan-cluster
# Description:       Start/stop configure-chanchan-cluster
### END INIT INFO

. /lib/lsb/init-functions

# config from IDM to chanchan: orgs, app
IDM_CONFIG='/config/idm2chanchan.json'  
CC_APP_CLIENT_PATH="fiware-chanchan/client"
DEPLOY_USER=bitergia

if [ -f "${IDM_CONFIG}" ]; then
    su - ${DEPLOY_USER} -c "cp ${IDM_CONFIG} ${CC_APP_CLIENT_PATH}/app"
fi
