# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.hostname = "server.vagrant"
    ubuntu.vm.network "private_network", ip: "192.168.42.10"
    ubuntu.vm.provision "shell" do |shell|
        shell.path = "scripts/bootstrap.sh"
    end
    # Use VBoxManage to customize the VM. For example to change memory:
    ubuntu.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  config.vm.define "centos" do |centos|
    centos.vm.box_url = "http://files.brianbirkinbine.com/vagrant-centos-65-x86_64-minimal.box"
    centos.vm.box = "centos/65"
    centos.vm.hostname = "server.vagrant"
    centos.vm.network "private_network", ip: "192.168.42.11"
    # Use VBoxManage to customize the VM. For example to change memory:
    centos.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
      vb.customize ["modifyvm", :id, "--hpet", "on"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end
    centos.vm.provision "shell" do |shell|
        shell.path = "scripts/bootstrap.sh"
    end
  end
end
