#!/bin/bash
# To be executed on startup to configure cygnus cluster
### BEGIN INIT INFO
# Provides:          configure-cygnus-cluster
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop configure-cygnus-cluster
# Description:       Start/stop configure-cygnus-cluster
### END INIT INFO

. /lib/lsb/init-functions

# Subscribe to orion host for receive notifications
ORION_HOSTNAME=orion
ORION_PORT=1026
CYGNUS_HOSTNAME=`hostname -i` # can't link orion to cygnus (circular link in docker). Use IP

# For all the organizations, subscribe to all changes to entities with names manual:*
# To change to params: type:org_name
(curl ${ORION_HOSTNAME}:${ORION_PORT}/NGSI10/subscribeContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "entities": [
        {
            "type": "org_a",
            "isPattern": "true",
            "id": "manual:*"
        }
    ],
    "attributes": [
        "temperature"
    ],
    "reference": "http://${CYGNUS_HOSTNAME}:5001/notify",
    "duration": "P1M",
    "notifyConditions": [
        {
            "type": "ONCHANGE",
            "condValues": [
                "pressure"
            ]
        }
    ],
    "throttling": "PT1S"
}
EOF

(curl ${ORION_HOSTNAME}:${ORION_PORT}/NGSI10/subscribeContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "entities": [
        {
            "type": "org_b",
            "isPattern": "true",
            "id": "manual:*"
        }
    ],
    "attributes": [
        "temperature"
    ],
    "reference": "http://${CYGNUS_HOSTNAME}:5002/notify",
    "duration": "P1M",
    "notifyConditions": [
        {
            "type": "ONCHANGE",
            "condValues": [
                "pressure"
            ]
        }
    ],
    "throttling": "PT1S"
}
EOF

# Santander sensors
(curl ${ORION_HOSTNAME}:${ORION_PORT}/NGSI10/subscribeContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "entities": [
        {
            "type": "santander:soundacc",
            "isPattern": "true",
            "id": "urn:smartsantander:testbed:*"
        }
    ],
    "reference": "http://${CYGNUS_HOSTNAME}:5050/notify",
    "duration": "P1M",
    "notifyConditions": [
        {
            "type": "ONCHANGE",
            "condValues": [
                "TimeInstant"
            ]
        }
    ]
}
EOF

# IDAS temperature sensors
(curl ${ORION_HOSTNAME}:${ORION_PORT}/NGSI10/subscribeContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "entities": [
        {
            "type": "thing",
            "isPattern": "true",
            "id": "SENSOR_TEMP:*" 
        }
    ],
    "attributes": [
        "temperature" 
    ],
    "reference": "http://${CYGNUS_HOSTNAME}:6001/notify",
    "duration": "P1M",
    "notifyConditions": [
        {
            "type": "ONCHANGE",
            "condValues": [
                "TimeInstant" 
            ]
        }
    ],
    "throttling": "PT1S" 
}
EOF