orion:
    image: bitergia/orion
idmauthlegacy:
    image: bitergia/idmauthlegacy
    volumes:
        - /config
chanchanapp:
    image: bitergia/chanchanapp
    links:
        - idmauthlegacy
        - cygnus
        - orion
    volumes_from:
        - idmauthlegacy
cygnus:
    image: bitergia/cygnus
    links:
        - orion
