mongodbdata:
    image: bitergia/mongodb:2.6
    volumes:
        - /var/lib/mongo
    restart: no
    entrypoint: ["/bin/echo","Data-only container for mongodb"]

mongodb:
    image: bitergia/mongodb:2.6
    volumes_from:
        - mongodbdata
    expose:
        - "27017"
orion:
    image: bitergia/fiware-orion:0.22.0
    links:
        - mongodb
    expose:
        - "10026"

idasiotacpp:
    image: bitergia/idas-iota-cpp:1.2.0
    links:
        - mongodb
        - orion
    expose:
        - "8080"
        - "8081"

idasiotalwm2m:
    image: bitergia/idas-iota-lwm2m:0.2.0
    links:
        - mongodb
        - orion
    expose:
        - "4041"