authzforce:
    image: bitergia/authzforce:4.2.0
    expose:
        - "8080"

idm:
    image: bitergia/idm-keyrock:4.3.0
    links:
        - authzforce
    volumes:
        - /config
    expose:
        - "5000"
