mongodbdata:
    image: bitergia/mongodb:3.0
    volumes:
        - /var/lib/mongo
    restart: no
    entrypoint: ["/bin/echo","Data-only container for mongodb"]

mongodb:
    image: bitergia/mongodb:3.0
    volumes_from:
        - mongodbdata
    expose:
        - "27017"
orion:
    image: bitergia/fiware-orion:0.22.0
    links:
        - mongodb
    expose:
        - "10026"
