mongodbdata:
    image: bitergia/mongodb:2.6
    volumes:
        - /var/lib/mongo
    restart: no
    entrypoint: ["/bin/echo","Data-only container for mongodb"]

mongodb:
    image: bitergia/mongodb:2.6
    volumes_from:
        - mongodbdata
    expose:
        - "27017"

authzforce:
    image: bitergia/authzforce
    expose:
        - "8080"

idm:
    image: bitergia/idm
    links:
        - authzforce
    volumes:
        - /config
    expose:
        - "5000"

pepwilma:
    image: bitergia/pep-wilma
    links:
        - orion
        - idm
        - authzforce
