mongodbdata:
    image: bitergia/mongodb-org:2.6
    volumes:
        - /var/lib/mongo
    restart: no
    entrypoint: ["/bin/echo","Data-only container for mongodb"]

mongodb:
    image: bitergia/mongodb-org:2.6
    volumes_from:
        - mongodbdata
    expose:
        - "27017"
orion:
    image: bitergia/orion:0.22.0
    links:
        - mongodb

authzforce:
    image: bitergia/authzforce
    expose:
        - "8080"

wilmapep:
    image: bitergia/wilma-pep
    links: 
        - orion
        - idm
        - authzforce

idm:
    image: bitergia/idm
    links:
        - authzforce
